name: Output info
on: [issues]
jobs:
    info:
     runs-on: ubuntu-latest
     steps:
        - name: Get Code
          uses: actions/checkout@v3
        - name: Install nodejs
          uses: actions/setup-node@v3
        - name: install dependencies
          run: npm ci
        - name: Output Github context
          run: echo "${{ toJSON(github.event) }}"
